# Generated by Django 4.2 on 2023-04-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=25, unique=True, verbose_name='Topic')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('publish_date', models.DateField(verbose_name='Date Publised')),
                ('content', models.TextField(max_length=2200, verbose_name='Synopsis')),
                ('purchase_link', models.URLField(verbose_name='Link to Purchase')),
                ('topic', models.ManyToManyField(blank=True, to='website.topic')),
            ],
        ),
    ]
