# Generated by Django 4.2 on 2023-04-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_blogpost_purchase_link_blogpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(auto_now_add=True, verbose_name='Published'),
        ),
    ]
