# Generated by Django 4.2 on 2023-04-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_blogpost_click_bait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='topic',
        ),
    ]
