# Generated by Django 4.2 on 2023-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_blogpost_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.ManyToManyField(blank=True, to='website.topic'),
        ),
    ]
