# Generated by Django 4.2 on 2023-04-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blogpost_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=None, upload_to='blog_images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
