# Generated by Django 4.2 on 2023-04-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='link',
            field=models.URLField(blank=True, default=None, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
