# Generated by Django 4.2 on 2023-04-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_blogpost_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='link',
        ),
    ]
