# Generated by Django 4.2 on 2023-04-14 13:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_blogpost_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=2200, verbose_name='Content'),
        ),
    ]
